export interface InquiryTemplateData {
  facilityName: string;
  senderName: string;
  email: string;
  phone?: string;
  insurance?: string;
  notes: string;
}

export const emailTemplates = {
  /**
   * Generates HTML and Text templates for a new facility inquiry
   */
  newInquiry: (data: InquiryTemplateData) => {
    const text = `
You have a new inquiry from ${data.senderName}.

Facility: ${data.facilityName}
Email: ${data.email}
Phone: ${data.phone || "N/A"}
Insurance: ${data.insurance || "N/A"}

Notes:
${data.notes}
    `.trim();

    const html = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-w-xl mx-auto p-6 bg-white border border-gray-200 rounded-lg shadow-sm">
        <h2 style="color: #0f172a; margin-top: 0;">New Inquiry for ${data.facilityName}</h2>
        <p style="color: #475569; font-size: 16px;">You have received a new prospective patient inquiry from <strong>${data.senderName}</strong>.</p>
        
        <div style="background-color: #f8fafc; padding: 16px; border-radius: 8px; margin: 24px 0;">
          <h3 style="color: #334155; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em; margin-top: 0;">Contact Details</h3>
          <ul style="list-style: none; padding: 0; margin: 0; color: #1e293b;">
            <li style="margin-bottom: 8px;"><strong>Email:</strong> <a href="mailto:${data.email}" style="color: #2563eb;">${data.email}</a></li>
            <li style="margin-bottom: 8px;"><strong>Phone:</strong> ${data.phone || "Not provided"}</li>
            <li style="margin-bottom: 8px;"><strong>Insurance:</strong> ${data.insurance || "Not provided"}</li>
          </ul>
        </div>

        <div style="margin-top: 24px;">
          <h3 style="color: #334155; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em;">Message</h3>
          <div style="background-color: #ffffff; padding: 16px; border-left: 4px solid #cbd5e1; color: #334155; font-style: italic;">
            ${data.notes.replace(/\n/g, "<br>")}
          </div>
        </div>

        <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 32px 0;" />
        <p style="color: #94a3b8; font-size: 12px; text-align: center;">
          This email was securely generated by the Aldora platform.<br>
          Please do not reply directly to this automated email address.
        </p>
      </div>
    `;

    return { subject: `New Inquiry for ${data.facilityName}`, html, text };
  },

  /**
   * Generates HTML and Text templates for sending a confirmation to the user
   */
  inquiryConfirmation: (data: InquiryTemplateData & { facilityPhone?: string, facilityEmail?: string }) => {
    const text = `
Hello ${data.senderName},

Thank you for your interest in ${data.facilityName}. We have successfully received your inquiry!
The admissions team will review your details and reach out to you shortly.

Facility Details:
${data.facilityName}
Phone: ${data.facilityPhone || "Not provided"}
Email: ${data.facilityEmail || "Not provided"}

Your Message:
${data.notes}

Best regards,
The Aldora Platform
    `.trim();

    const html = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-w-xl mx-auto p-6 bg-white border border-gray-200 rounded-lg shadow-sm">
        <h2 style="color: #0f172a; margin-top: 0; text-align: center;">Inquiry Received</h2>
        <p style="color: #475569; font-size: 16px;">Hello <strong>${data.senderName}</strong>,</p>
        <p style="color: #475569; font-size: 16px;">Thank you for your interest in <strong>${data.facilityName}</strong>. We have successfully received your inquiry and securely passed it to their admissions team.</p>
        
        <div style="background-color: #f0fdf4; border: 1px solid #bbf7d0; padding: 16px; border-radius: 8px; margin: 24px 0;">
          <h3 style="color: #166534; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em; margin-top: 0;">What's Next?</h3>
          <p style="color: #15803d; margin-bottom: 0;">The facility's staff will review your information (including your insurance details) and contact you shortly to discuss availability, pricing, and next steps.</p>
        </div>

        <div style="margin-top: 24px;">
          <h3 style="color: #334155; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em;">Facility Contact Details</h3>
          <ul style="list-style: none; padding: 0; margin: 0; color: #1e293b;">
            <li style="margin-bottom: 8px;"><strong>Phone:</strong> ${data.facilityPhone || "Not provided"}</li>
            <li style="margin-bottom: 8px;"><strong>Email:</strong> ${data.facilityEmail ? `<a href="mailto:${data.facilityEmail}" style="color: #2563eb;">${data.facilityEmail}</a>` : "Not provided"}</li>
          </ul>
        </div>

        <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 32px 0;" />
        <p style="color: #94a3b8; font-size: 12px; text-align: center;">
          This email was securely generated by the Aldora platform.<br>
          Please do not reply directly to this automated email address.
        </p>
      </div>
    `;

    return { subject: `Inquiry Received - ${data.facilityName}`, html, text };
  },
};
